# Generated by Django 3.2 on 2023-06-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230622_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='meta_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='meta_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
